### ISSUE TITLE
[BUG] Wepack Loader resolution

### ISSUE THREAD

**Issue by AniketHQ** [MobileReality/react-native-select-pro#139]
**Describe the bug**
I installed the package according to the required steps but after restarting the server, I am getting 'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.' error in console.

**To Reproduce**
1. Install the npm package
2. Restart the expo server
3. Open the web platform for expo using 'w' key press
4. See error in console

**Expected behavior**
It should work as shown in the expo snack example

**Screenshots**
<img width="1438" alt="Screenshot 2022-12-05 at 4 57 37 PM" src="https://user-images.githubusercontent.com/106660073/205626506-bc361727-bfa8-483c-86f3-b4944636ca14.png">

**Environment (please complete the following information):**
 - Expo: ~47.0.8
 - React Native Version: 0.70.5
 - Device on which issue is presented: Web

**Comment by irekrog** [comment]
Hi @AniketHQ  
I think you have an issue with webpack / babel config, please try this: https://stackoverflow.com/a/72519431

**Comment by younes0** [comment]
I guess you are using Expo and this is a know problem: https://github.com/expo/expo/issues/19677
As workaround, you need to edit webpack.config.js :

```js
const createExpoWebpackConfigAsync = require("@expo/webpack-config");
module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(
    {
      ...env,
      babel: {
        dangerouslyAddModulePathsToTranspile: [ "react-native-select-pro"]
      },
    },
    argv
  );
  return config;
};
```
