### ISSUE TITLE
enable customization on SelectFieldType

### ISSUE THREAD

**Issue by luccasr73** [MobileReality/react-native-select-pro#195]
**Is your feature request related to a problem? Please describe.**
Customize styles on SelectFieldType, this component a have default padding that i need to remove https://github.com/luccasr73/react-native-select-pro/blob/master/packages/react-native-select-pro/src/components/select-field-type/select-field-type.tsx#L44

<img width="354" alt="Screenshot 2023-02-26 at 18 00 23" src="https://user-images.githubusercontent.com/25834066/221437008-b3e1fc56-e132-4564-8332-8fdfe3cf7b31.png">

**Describe the solution you'd like**
possibility to pass style props and customize SelectFieldType

**Describe alternatives you've considered**
I'm currently using a hack with negative margin to get the result I need
```
 const styles = {
    arrow: {
      container: {
        marginHorizontal: -12,
      },
    },
    text: {
      fontSize: 16,
      marginHorizontal: -12,
    },
  };
```
<img width="355" alt="Screenshot 2023-02-26 at 17 55 10" src="https://user-images.githubusercontent.com/25834066/221436737-f37723ff-d418-42e0-be81-12da42f21c59.png">

**Comment by irekrog** [comment]
Hi @luccasr73 thanks for reporting, we will investigate this issue

**Comment by luccasr73** [comment]
i can do a pr fixing this?

**Comment by irekrog** [comment]
@luccasr73 
Sure, would be great

**Comment by irekrog** [comment]
@luccasr73 
This issue has been fixed, `styles={{ select: { container: { paddingHorizontal: 0 }}}}` is working now in v2.1.2

**Comment by luccasr73** [comment]
thanks @irekrog
