### ISSUE TITLE
[BUG] select-modal expo example not working

### ISSUE THREAD

**Issue by imdkbj** [MobileReality/react-native-select-pro#203]
**Describe the bug**
select-modal expo example not working

**To Reproduce**
Steps to reproduce the behaviour :
1. Go to https://mobilereality.github.io/react-native-select-pro/docs/api/select-modal
2. Click on Either own device or ios/android
3. App will crash on device/expo.

**Expected behaviour**
Should to work

**Comment by imdkbj** [comment]
> @imdkbj Can you check again ? I can't reproduce this issue, expo is working fine for me. (Although there is styling issue in this example)

<img width="937" alt="image" src="https://user-images.githubusercontent.com/46839821/232057666-04cc86fa-464a-44ac-aa34-25e7b5971ebc.png">

Same on device too.

**Comment by kkaplinski** [comment]
Yes, this is just styling issue. We will fix that. Button is rendering under status bar. You can add `marginTop: 40` to button for now.
