### ISSUE TITLE
[BUG] SelectModalProvider not working in IOS

### ISSUE THREAD

**Issue by danish5454** [MobileReality/react-native-select-pro#227]
**Describe the bug**
A clear and concise description of what the bug is when you open modal and click the list but do not select anything and click any where in the screen to close the select list and then try to Hide modal in **IOS**.

**To Reproduce**
1. Go to your Modal provider link `https://themobilereality.com/react-native-select-pro-docs`
2. Just open your own example in expo.
3. open the list and just close it by clicking anywhere and just **click hide modal** you will see the **BUG**

**Expected behavior**
Modal will close.

**Environment (please complete the following information):**
 - OS: [iOS/Android]
 - OS Version: [eq. iOS 14]
 - React Native Version
 - Device on which issue is presented

**Additional context**

https://github.com/MobileReality/react-native-select-pro/assets/132438054/c598d348-06df-4362-a480-a1b59c86bee0

**Comment by gitsad** [comment]
Probably related to:
https://github.com/facebook/react-native/issues/16182
https://github.com/facebook/react-native/issues/33733
https://github.com/facebook/react-native/issues/34184

**Comment by gitsad** [comment]
Thanks @danish5454 for raising it.
