### ISSUE TITLE
 [BUG] Unable to display Options List by default

### ISSUE THREAD

**Issue by TheProgamererZ** [MobileReality/react-native-select-pro#238]
Hi all , needed some help. I am new here so apologies for any inconvenience.
I am using the React-Native-Select-Pro for my app. The default action of the module is that the optionsList is opened on clicking the drop-down icon on the Select Container. 
But , I want to keep the Options List open by default , without having to click on the icon to open it. Tried the 'open' prop , but it only seems to fire functions when the optionsList is opened. 

Any way to keep the Options List open by default , without having to click on the icon to open it? 

Much Appreciated. Thanks!

 - OS: [iOS/Android]
 - React Native Version - '0.72.6'
 - @mobile-reality/react-native-select-pro version : '^2.2.3'
 - expo version : '49.0.21'

````
<Select
clearable={true}
searchable={true}  
options={list}
onSelect={(item) =\> setItem(item)}
placeholderText='Search Item'
styles={{
select:{
container:{
backgroundColor:”skyblue”  
}
},
option:{
container:{
backgroundColor:”green”,
},
text:{
fontSize:14,
}
},
optionsList:{
Padding:10
}
}} /\>
````

**Comment by danish5454** [comment]
@TheProgamererZ try tp pass ref in `Select`.

`const selectRef = React.useRef<Select>(null)`;


 `useEffect(() => {
    ref.current = selectRef.current?.open();
  }, []);`

**Comment by gitsad** [comment]
@TheProgamererZ Let us know if @danish5454 suggestion helped. Now I'm closing this ticket.
