### ISSUE TITLE
[BUG] When the drop down is opened and the user tries to scroll, the drop down "floats"

### ISSUE THREAD

**Issue by sizuf** [MobileReality/react-native-select-pro#241]
**Describe the bug**
When nested inside ScrollView and the drop down is opened, if the user tries to scroll, the drop down "floats", i.e doesn't stay attached. Can be seen better on the videos  bellow. 

**To Reproduce**
1. Create a ScrollView component. 
2. Add Select inside.
3. Add some options to the select.
4. While the drop down is opened, try to scroll outside.

**Expected behavior**
The drop down should not move.

**Video**

https://github.com/MobileReality/react-native-select-pro/assets/12835449/b8cb2eff-a907-4673-b47c-629453bc009e

https://github.com/MobileReality/react-native-select-pro/assets/12835449/29b16ff9-bd57-4ed9-b594-ac32b713e6e2

**Environment (please complete the following information):**
 - OS: iOS/Android
 - OS Version: iOS 17, Android 14, but probably affects all versions
 - React Native Version: v0.73.6

**Comment by dawidgierdal** [comment]
@sizuf Could you share a snippet of your code? I would like to see what props you pass to Select, preferably share the entire view. When select is enabled, the ability to scroll the screen should not be possible. I see in your videos that you can scroll with select enabled.

**Comment by danish5454** [comment]
@sizuf try to disable scrollView by using property `onSelectOpened` and to enable again you also have callback `onSelectClosed`.
It's not a good approach when dropdown is opened and behind View is still scrollable.

**Comment by dawidgierdal** [comment]
@sizuf 
When using ScrollView together with Select, there are two key things to keep in mind.

First, the SelectProvider must be placed above the ScrollView in the component hierarchy. (Check out the video: example1)

Second, it's important to ensure that SelectProvider is not duplicated across different parts of the application, as this can cause issues with calculating the position of the dropdown menu.  (Check out the video: example2)
[examples.zip](https://github.com/user-attachments/files/16836356/examples.zip)

**Comment by gitsad** [comment]
Hi @sizuf like @dawidgierdal has said, please check your codebase based on this. When your issue still persist then let us know and please provide a reproduction. For know I'm closing this issue. Here you can find proper implementation with ScrollView: https://github.com/MobileReality/react-native-select-pro/pull/250 .
