### ISSUE TITLE
[BUG] Incorrect options list position

### ISSUE THREAD

**Issue by marko-mihajlovic** [MobileReality/react-native-select-pro#242]
**Describe the bug**
I just migrated from expo 49 to 51. But now, it seems like the position of dropdown list is not same on all devices, and is shown over the input. In previous versions it worked. Seems like there was some RN change that causes this issue. You can see [commit history](https://github.com/marko-mihajlovic/rn-select-pro-issue/commits/main/) where I tried different versions.

**To Reproduce**
- Launch [basic](https://mobilereality.github.io/react-native-select-pro/docs/usage#basic) example on Android.
- Minimal reproducible code: [rn-select-pro-issue](https://github.com/marko-mihajlovic/rn-select-pro-issue)

**Expected behavior**
Dropdown list should be shown below input, on all devices.

**Screenshots**
First device:
<img src="https://github.com/MobileReality/react-native-select-pro/assets/88029880/406dc3e2-79d6-47ce-a428-294c0a0fc79f" height="180">
<img src="https://github.com/MobileReality/react-native-select-pro/assets/88029880/feb0c02b-2e98-4329-9cde-8a1074f720d5" height="180">

Second device:
<img src="https://github.com/MobileReality/react-native-select-pro/assets/88029880/3453740a-1520-46f3-851e-0a1bf74abfaf" height="180">
<img src="https://github.com/MobileReality/react-native-select-pro/assets/88029880/926bfb5f-41cf-4b77-849a-25e9a674c24a" height="180">

**Environment:**
 - OS: Android
 - React Native Version: 0.74.3

**Comment by marko-mihajlovic** [comment]
It's also incorrect when shown above input:

![image](https://github.com/MobileReality/react-native-select-pro/assets/88029880/001f0363-d9e4-438b-94f1-4d61486b9819)

**Comment by maormeno** [comment]
I am having the exact same problem with expo 48 and react native 0.71.14

**Comment by dawidgierdal** [comment]
this should help: https://github.com/MobileReality/react-native-select-pro/pull/248

**Comment by gitsad** [comment]
@marko-mihajlovic new release has been deployed: https://github.com/MobileReality/react-native-select-pro/releases/tag/@mobile-reality/react-native-select-pro@2.2.5

**Comment by maormeno** [comment]
thank you so much!
