### ISSUE TITLE
[BUG] "defaultOption" and "searchable" Select not displaying the preselected option

### ISSUE THREAD

**Issue by grmnlxndr** [MobileReality/react-native-select-pro#243]
**Describe the bug**
When having a Select component with both defaultOption and searchable props, the Select is rendered with the placeholder text instead of the defaultOption label.

`<Select options={DATA} defaultOption={{ label: 'Option 3', value: 'option3'}} searchable />`

**To Reproduce**
Check this Snack to see the current behavior: [Snack Demo](https://snack.expo.dev/QFwq-D5AEbdAuR8dgpYWM)

**Expected behavior**
The Select component should render the defaultOption label instead of the placeholder text.

**Screenshots**
The select when first rendered, it is not showing the default option, but the empty search field with the placeholder text:
![closed-select](https://github.com/user-attachments/assets/7e661ccd-47b6-49a0-9eb2-2586e03ad014)

When opening the select for the first time, it shows the default option selected in the option list:
![first-open-select](https://github.com/user-attachments/assets/1ac93124-2a0e-4391-9763-40c68105e78b)

**Environment (please complete the following information):**
 - OS: iOS/Android
 - OS Version: iOS 17
 - iPhone 14 and iPhone 15 simulator (not tested in other devices)

**Additional context**
Looks like the searchfield is not pre-populating the defaultOption's label when both options are enabled.

Thanks,

Germán

**Comment by dawidgierdal** [comment]
@grmnlxndr fix has been merged: https://github.com/MobileReality/react-native-select-pro/pull/245/files

**Comment by grmnlxndr** [comment]
Thanks Dawid!
