### ISSUE TITLE
[BUG] Certain props are not present in Select component

### ISSUE THREAD

**Issue by steve1316** [MobileReality/react-native-select-pro#41]
**Describe the bug**
Props like `searchable` and `scrollToSelectedOption` as shown in the [SelectProps page](https://mobilereality.github.io/react-native-select-pro/interfaces/SelectProps.html#searchable) in your docs are not present in the Select component as indicated by Typescript.

**To Reproduce**
1. Use v1.2.0
2. Type the following with data of your choice:
```
<SelectProvider>
    <Select options={data} searchable={true} />
</SelectProvider>
```
3. Typescript throws an error:
```
Property 'searchable' does not exist on type 'IntrinsicAttributes & SelectProps & RefAttributes<SelectRef>'.ts(2322)
```

**Expected behavior**
Typescript should not throw an error.

**Screenshots**
![Code_QYiFKU8Xnw](https://user-images.githubusercontent.com/18709555/147394818-c1e9ea68-8ab9-4924-8a4a-52b5889834f5.png)

**Comment by irekrog** [comment]
Hi @steve1316 
Thanks for reporting. This bug has been fixed in v1.3.0.
