### ISSUE TITLE
Different TextStyle for placeholder and selectedOption.

### ISSUE THREAD

**Issue by AlexanderLindkjaer** [MobileReality/react-native-select-pro#43]
**Is your feature request related to a problem? Please describe.**
In my design, a label/placeholder will have a different color than a selected value. Right now `selectControlTextStyle ` sets the given color for both the placeholder and selected option.

**Describe the solution you'd like**
Have a different style prop for the placeholder text like `placeholderTextStyle`

If this is already doable, please let my know 😃

**Comment by irekrog** [comment]
Hi @AlexanderLindkjaer 

At this moment you can't set other color for placeholder but it should be possible, so we'll add a new prop :) We'll let you know :)

**Comment by AlexanderLindkjaer** [comment]
@irekrog I just turned on search in one of my selects. No TextStyle prop reaches the search input either. I would be really nice to have a prop for that, or make that input inherit the `selectControlTextStyle` prop.

Let me know if you want a new issue for that one.

**Comment by irekrog** [comment]
@AlexanderLindkjaer yeah it was a bug and in the next version will be fixed, styles will be inherited. I think today or tommorrow new version will be on npm
