### ISSUE TITLE
Add tintcolor to Image 

### ISSUE THREAD

**Issue by Ruslan-BG** [MobileReality/react-native-select-pro#46]
**Is your feature request related to a problem? Please describe.**
I can't change the color of the picture chevron-down.png and x.png

**Describe the solution you'd like**
add props tintcolor chevron-down and x.png

**Describe alternatives you've considered**
I manually added to the style => file select-control/index.tsx  line 427 ->  styles.arrowIcon ->  tintColor:'#363853' and clear-option line 59 -> styles.xIcon -> tintColor:'#363853'

**Comment by irekrog** [comment]
Hi @Ruslan-BG 

Sure, we'll add new props

**Comment by Ruslan-BG** [comment]
Hi !
Thank you ! :)

**Comment by irekrog** [comment]
@Ruslan-BG 

for arrow I've just added `selectControlArrowImageStyle` prop
for x icon you can use `selectControlClearOptionImageStyle` prop

**Comment by Ruslan-BG** [comment]
Thank you very much!
